project:
  type: website
  execute-dir: project
  output-dir: _site
  render:
    - index.qmd
  preview:
    watch-inputs: true

execute:
  freeze: auto

repo-url: https://github.com/nballou/basic-needs-in-games
site-url: https://nballou.github.io/basic-needs-in-games/
data-url: https://doi.org/10.5281/zenodo.18349438
data-license: CC0